### PR TITLE
Slightly evolve package setup

### PR DESCRIPTION
**Pull request by yakutovicha**
- Replace `setup.json` with `setup.cfg`
- Keep the version number in a single place: `version.py`
- Remove redundant version check

### CODE REVIEW

**Review by eimrek — COMMENTED** [review]
Thanks. Couple of things:

1) You removed .github/check_version.py but it's still used in the pypi-publish.yml

2) Why not remove setup.cfg and fully move to pyproject.toml? E.g. [here](https://stackoverflow.com/questions/44878600/is-setup-cfg-deprecated) they seem to prefer a solution without setup.cfg. Also aiida-core uses only pyproject.toml

**Comment by yakutovicha** [comment]
> 1. You removed .github/check_version.py but it's still used in the pypi-publish.yml

Removed from there as well - thanks!

**Comment by yakutovicha** [comment]
> 2\. Why not remove setup.cfg and fully move to pyproject.toml? E.g. [here](https://stackoverflow.com/questions/44878600/is-setup-cfg-deprecated) they seem to prefer a solution without setup.cfg. Also aiida-core uses only pyproject.toml

Yeah, maybe that is the right thing to do. I will check what people say. To be honest, I am a little bit confused with python packaging solutions. So many options, but not sure which one is the best. Do you have an opinion on that?

**Comment by yakutovicha** [comment]
@eimrek `setup.json` and `setup.py` are replaced by `pyproject.toml` 👍

**Review by eimrek — APPROVED** [review]
Thanks! Fine to merge from my side. Although I don't really know which solution is the best, I hope i didn't influence you to implement a subpar approach.

**Comment by yakutovicha** [comment]
> Thanks! Fine to merge from my side. Although I don't really know which solution is the best, I hope i didn't influence you to implement a subpar approach.

I have some ideas, I will make an issue in our `general issues` repo to discuss them.

**Pull request merged**
